### ISSUE TITLE
RuntimeError('Please set API_URL environment variable')

### ISSUE THREAD

**Issue by kakamband** [vyahello/pep8-checker#4]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/app/.heroku/python/lib/python3.8/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/app/.heroku/python/lib/python3.8/site-packages/bottle.py", line 3650, in wrapper
    result = func(*args, **kwargs)
  File "/app/checker/__main__.py", line 51, in index
    url=api_url(), json={'code': code}
  File "/app/checker/__main__.py", line 17, in api_url
    raise RuntimeError('Please set API_URL environment variable')
RuntimeError: Please set API_URL environment variable

**Comment by vyahello** [comment]
Hey, this error was raised due to the fact that `AWS_ENDPOINT` environment variable was not set. You have to obtain it and set 
before the execution e.g:
```
export AWS_ENDPOINT=https://xxxxxx.execute-api.us-east-2.amazonaws.com/v1
python -m checker
```

**Comment by vyahello** [comment]
Close the issues as per comment above
